site_name: patminton
site_description: GPU-accelerated forward and adjoint operators for 3D photoacoustic tomography
site_url: https://patas.readthedocs.io/
repo_url: https://github.com/dotrungthai2001/patas
copyright: Copyright &copy; 2026 the patminton authors

theme:
  name: material
  features:
    - navigation.sections
    - navigation.top
    - content.code.copy
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

nav:
  - Home: index.md
  - Installation: installation.md
  - Quickstart: quickstart.md
  - Background:
      - Overview: background.md
      - Physical and mathematical model: theory.md
      - Transducer models: transducer-models.md
      - Reconstruction algorithms: solvers.md
      - Key parameters: parameters.md

exclude_docs: |
  requirements.txt

markdown_extensions:
  - admonition
  - attr_list
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
